# Where things are
source:       .
destination:  ./_site
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "/" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Aragron's blog
description: Recodrding life and waiting love for SuperM!.
keywords: Jekyll Theme
# url: http://Aragronsam.github.io
url: http://www.aragron.com
feed: /atom.xml
favicon: https://raw.githubusercontent.com/michaelliao/awesome-python3-webapp/day-03/www/favicon.ico

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 源动力
    url: /categories.html
  - text: 时光机
    url: /archives.html
  - text: 链接
    url: /links.html  
  - text: 关于我
    url: /contact.html

#Author config
author:
    name: aragron
    email: aragronvip@163.com
    imageLink: http://rab41f8zg.hd-bkt.clouddn.com/img/head_photo.jpg
    simpleIntro: 一只爱思考的螃蟹座。
    detailIntro:
      <p>胆小认生，不宜相处！</p>
      <p>每一颗大树，都曾只是一粒种子。</p>
      <p>幸福是否只是一种传说，永远都找不到。</p>
      <p>人生是场马拉松, 好运, 歹运, 终究是会均值回归的!</p>
      <p>Motto：Clam down，there's always we out and no reason not follow your heart!</p>
      <p>Address:黄冈罗田；Graduate:湖北师范大学2015</p>
      <p>QQ:342279465；WeChat ID:aragron555</p>
      <p>Weibo ID:aragron</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/Sambrave  
  - class: icon-github-alt
    url: http://github.com/Aragronsam
  - class: icon-coffee
    url: https://getpocket.com/a/queue/
  - class: icon-comments
    url: https://wx.qq.com/

#Links
customLinks:
  - item:    
    - text: 大屁股
      url: https://mp.weixin.qq.com/s/WlQ16Be8t4pdjPu3I1ZE_w
    - text: 让鸡毛飞
      url: https://m.toutiaocdn.com/i6931932048873554436/?app=news_article&timestamp=1647905682&use_new_style=1&req_id=202203220734410101420381330C11FCA2&group_id=6931932048873554436
    - text: 百度
      url: http://www.baidu.com/    
    - text: 日历
      url: https://www.baidu.com/s?wd=2022+%E6%97%A5%E5%8E%86&tn=84053098_3_dg&ie=utf-8
    - text: 阮一峰
      url: http://www.ruanyifeng.com/
    - text: 廖雪峰
      url: http://www.liaoxuefeng.com/
    - text: 峰
      url: https://www.comellia.com/
    - text: 浩
      url: https://fhaoer.com/
    - text: IDEA
      url: https://youmeek.gitbooks.io/intellij-idea-tutorial/content/debug-introduce.html
    - text: Macwk
      url: https://www.macwk.com/
    - text: 阿里云
      url: https://home.console.aliyun.com/#/
    - text: 极客时间
      url: https://time.geekbang.org/learning/path
    - text: 程序员
      url: http://blog.didispace.com/
    - text: 虫子的快乐
      url: https://mp.weixin.qq.com/cgi-bin/home?t=home/index&lang=zh_CN&token=1535205318
    - text: 美团
      url: https://tech.meituan.com
    - text: 七牛
      url: https://portal.qiniu.com/kodo/bucket/overview?bucketName=aragronpic0315
    - text: 奇客谷
      url: https://www.qikegu.com
    - text: 手册网
      url: http://www.shouce.ren/api/view/a/6409
    - text: 辉_email
      url: http://mail.yonghui.cn/coremail/XT3/index.jsp?sid=BAZNEayTlgNItaCSFoTTcrhoOfjKtXha#/md=folder&_suid=121
    - text: CHEN川
      url: https://www.hicsc.com/about
    - text: 芋道源码
      url: http://www.iocoder.cn/
    - text: vip源码
      url: http://svip.iocoder.cn/index/
    message: Friends
  - item:
    - text: Toolbox
      url: http://www.atoolbox.net/Category.php?Id=23
    - text: Boot
      url: https://gitbook.cn/gitchat/column/5b86228ce15aa17d68b5b55a/topic/5baca87d80460e6b3d6f7abc
    - text: Oschina
      url: https://www.oschina.net/project/top_cn_2019?utm_source=gitee_ad
    - text: W3school
      url: http://www.w3school.com.cn/  
    - text: Mashibing
      url: https://www.mashibing.com/subject/1
    - text: Stackoverflow
      url: http://stackoverflow.com/  
    - text: Boot51
      url: http://blog.51cto.com/cloumn/detail/4
    - text: PEL
      url: https://space.bilibili.com/50329337?from=search&seid=10856009663831645711&spm_id_from=333.337.0.0
    - text: Cyberpunk
      url: https://www.cyberpunk.net/cn/zh-cn/
    - text: Http Requester
      url: https://packagecontrol.io/packages/Http%20Requester     
    - text: Scotch
      url: https://scotch.io/
    - text: Pizn
      url: http://pizn.github.io/kunka/contact.html
    - text: Codecademy
      url: https://www.codecademy.com/en/courses/learn-sql/lessons/manipulation/exercises/relational-databases
    - text: Vuepress
      url: https://doc.xugaoyi.com/pages/0fc1d2/
    - text: Jsfiddle      
      url: http://jsfiddle.net/BXZk2/
    - text: JQuery      
      url: https://oscarotero.com/jquery/
    - text: Go
      url: https://class.imooc.com/sale/go
    - text: Morty
      url: https://space.bilibili.com/393260578/video
    message: Others

#googleAnaly, your id link UA-12345678-X
#googleAnaly:
#  config: false
#  id: UA-40169250-1

#comment config
disqus:
  config: false
  id: aragron

duoshuo:
  config: true
  id: aragron

theme: jekyll-theme-merlot
