# Where things are
source:       .
destination:  ./_site
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "/" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Aragron's blog
description: Recodrding life and waiting love for SuperM!.
keywords: Jekyll Theme
# url: http://Aragronsam.github.io
url: http://www.aragron.com
feed: /atom.xml
favicon: https://raw.githubusercontent.com/michaelliao/awesome-python3-webapp/day-03/www/favicon.ico

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 源动力
    url: /categories.html
  - text: 时光机
    url: /archives.html
  - text: 链接
    url: /links.html  
  - text: 关于我
    url: /contact.html

#Author config
author:
    name: aragron
    email: 342279465@qq.com
    imageLink: http://s3s4mtyq6.hd-bkt.clouddn.com/img/head_photo.jpg
    simpleIntro: 一只爱思考の螃蟹座。
    detailIntro:
      <p>每一颗大树，都曾只是一粒种子。</p>
      <p>Motto：Clam down，there's always we out and no reason not follow your heart!</p>
      <p>Address:黄冈罗田；Graduate:湖北师范大学2015</p>
      <p>WeChat ID:aragron555</p>
      <p>    Phone:13122631521</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/Sambrave  
  - class: icon-github-alt
    url: http://github.com/Aragronsam
  - class: icon-coffee
    url: https://getpocket.com/a/queue/
  - class: icon-comments
    url: https://wx.qq.com/

#Links
customLinks:
  - item:    
    - text: 股社区
      url: https://mp.weixin.qq.com/s/YN7k0L1SFOyzooG5GO1mzQ
    - text: 让鸡毛飞
      url: https://m.toutiaocdn.com/i6931932048873554436/?app=news_article&timestamp=1647905682&use_new_style=1&req_id=202203220734410101420381330C11FCA2&group_id=6931932048873554436
    - text: 百度
      url: http://www.baidu.com/    
    - text: 日历
      url: https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&tn=84053098_3_dg&wd=2023%20%E6%97%A5%E5%8E%86&oq=2022%2520%25E6%2597%25A5%25E5%258E%2586&rsv_pq=e5abc9b8000e0dc5&rsv_t=44bcW5rBPDLFUqGfvwuvglYfyQvr8u617Dk3wecMrhdtdLQtjMk7QoHbbjAIGLI7WR7pqw&rqlang=cn&rsv_enter=1&rsv_dl=tb&rsv_sug3=3&rsv_sug1=3&rsv_sug7=100&rsv_sug2=0&rsv_btype=t&inputT=604&rsv_sug4=1772
    - text: 阮一峰
      url: http://www.ruanyifeng.com/
    - text: 廖雪峰
      url: http://www.liaoxuefeng.com/
    - text: 峰
      url: https://www.comellia.com/
    - text: 浩
      url: https://fhaoer.com/
    - text: Topbook
      url: https://topbook.cc/overview
    - text: Macwk
      url: https://www.macwk.com/
    - text: 阿里云
      url: https://home.console.aliyun.com/#/
    - text: 腾讯文档
      url: https://docs.qq.com/desktop/?u=986998b160dc470a93cb4579f9f7c49d
    - text: 知识星球
      url: https://wx.zsxq.com/dweb2/login
    - text: 小鸡词典
      url: https://jikipedia.com
    - text: 美团
      url: https://tech.meituan.com
    - text: 七牛
      url: https://portal.qiniu.com/kodo/bucket
    - text: 奇客谷
      url: https://www.qikegu.com
    - text: 手册网
      url: http://www.shouce.ren/api/view/a/6409
    - text: 辉
      url: http://mail.yonghui.cn/coremail/XT3/index.jsp?sid=BAZNEayTlgNItaCSFoTTcrhoOfjKtXha#/md=folder&_suid=121
    - text: CHEN川
      url: https://www.hicsc.com/about
    - text: 芋道源码
      url: http://www.iocoder.cn/
    - text: vip源码
      url: http://svip.iocoder.cn/index/
    message: Go
  - item:
    - text: Toolbox
      url: http://www.atoolbox.net/Category.php?Id=23
    - text: Boot
      url: https://gitbook.cn/gitchat/column/5b86228ce15aa17d68b5b55a/topic/5baca87d80460e6b3d6f7abc
    - text: Feixiaohao
      url: https://www.feixiaohaobtc.com
    - text: W3school
      url: http://www.w3school.com.cn/  
    - text: Google
      url: https://www.google.com
    - text: Fontawesome
      url: https://fontawesome.com/search?favorites=staff
    - text: Boot51
      url: http://blog.51cto.com/cloumn/detail/4
    - text: PEL
      url: https://space.bilibili.com/50329337?from=search&seid=10856009663831645711&spm_id_from=333.337.0.0
    - text: Cyberpunk
      url: https://www.cyberpunk.net/cn/zh-cn/
    - text: Http Requester
      url: https://packagecontrol.io/packages/Http%20Requester     
    - text: Scotch
      url: https://scotch.io/
    - text: Pizn
      url: http://pizn.github.io/kunka/contact.html
    - text: Codecademy
      url: https://www.codecademy.com/en/courses/learn-sql/lessons/manipulation/exercises/relational-databases
    - text: Vuepress
      url: https://doc.xugaoyi.com/pages/0fc1d2/
    - text: Jsfiddle      
      url: http://jsfiddle.net/BXZk2/
    - text: Flaticon
      url: https://www.flaticon.com/stickers-pack/animals-139
    - text: OKX
      url: https://www.okx.com/trade-spot/btc-usdt
    - text: Morty
      url: https://space.bilibili.com/393260578/video
    message: Others

#googleAnaly, your id link UA-12345678-X
#googleAnaly:
#  config: false
#  id: UA-40169250-1

#comment config
disqus:
  config: false
  id: aragron

duoshuo:
  config: true
  id: aragron

theme: jekyll-theme-merlot
